### PR TITLE
Issue/3325 modules v2 in v1 path explainer

### LINKED ISSUE #3325: add explainer for v2 found in v1 module path exception
This exception was introduced in #3304 but it was kept very generic. Add an explainer to be more informative, including all possible scenarios.

### PR DESCRIPTION
**Pull request by sanderr**
# Description

- Restructured `inmanta.compiler.help.explainer` to be more generic and more strictly (and correctly) typed.
- Introduced explainer for when a v2 module is found in the v1 module path

@wouterdb since we've talked about this before I'm requesting your review first, with an initial focus on the quality and completeness of the explanation. I'm not sure I've covered all potential scenario's. Once we've converged on this part I'll add @arnaudsjs for the full review. If you feel like an in-person discussion about the explanation would be useful, I'm available for that.

If you feel like the explainer improvements should go into iso4 to more easily add explainers to both master and iso4 (without conflicts) in the future, let me know.

closes #3325

# mypy-diff

(red is good, the green one on the last line was previously present but hidden)
```diff
+ stubs/asyncpg/types.pyi:5: error: Skipping analyzing 'asyncpg.pgproto.types': found module but no type hints or library stubs  [import]
- stubs/asyncpg/types.pyi:5: error: Skipping analyzing 'asyncpg.pgproto.types': found module but no type hints or library stubs  [import]
- src/inmanta/compiler/help/explainer.py:99: error: Argument 2 to "__init__" of "JinjaExplainer" has incompatible type "Type[ModifiedAfterFreezeException]"; expected "Type"  [arg-type]
- src/inmanta/compiler/help/explainer.py:102: error: "CompilerException" has no attribute "stmt"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:104: error: "CompilerException" has no attribute "stmt"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:105: error: "CompilerException" has no attribute "attribute"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:106: error: "CompilerException" has no attribute "stmt"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:109: error: "CompilerException" has no attribute "stmt"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:111: error: "CompilerException" has no attribute "attribute"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:112: error: "CompilerException" has no attribute "stmt"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:115: error: "CompilerException" has no attribute "stmt"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:116: error: "CompilerException" has no attribute "attribute"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:116: error: "CompilerException" has no attribute "stmt"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:120: error: "CompilerException" has no attribute "attribute"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:121: error: "CompilerException" has no attribute "instance"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:122: error: "CompilerException" has no attribute "resultvariable"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:123: error: "CompilerException" has no attribute "value"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:125: error: "CompilerException" has no attribute "reverse"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:126: error: "CompilerException" has no attribute "reverse"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:127: error: "CompilerException" has no attribute "resultvariable"  [attr-defined]
+ src/inmanta/compiler/help/explainer.py:150: error: Item "None" of "Optional[RelationAttribute]" has no attribute "get_name"  [union-attr]
```

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] ~~Sufficient test cases (reproduces the bug/tests the requested feature)~~
- [x] Correct, in line with design
- [x] ~~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

### CODE REVIEW

File: src/inmanta/compiler/help/templates/module_v2_in_v1_path.j2 [hunk 1]
```diff
@@ -0,0 +1,11 @@
+This error occurs when a v2 module was found in v1 modules path. To resolve this you should either convert this module to be v1
+or install it as a v2 module and set up your project accordingly.
+
+If you want to use the module as a v1 module, make sure to use the v1 cookiecutter template to create new modules.
+
+If you want to use the module as a v2 module:
```
Comment (wouterdb) [inline src/inmanta/compiler/help/templates/module_v2_in_v1_path.j2:6]: I would add a branch to the logic for
```
Is this a module you are developing yourself:
  -> editable install
otherwise
  -> rest
```

**Review by wouterdb — APPROVED** [review]

File: src/inmanta/compiler/help/templates/module_v2_in_v1_path.j2 [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+{% if project and not v2_source_configured -%}
+- set up your project with a module source of type "package" (see documentation)
+{% endif -%}
+- if you would like to work in editable mode on a local copy of the module, run `inmanta module install {{ path }}`
```
[the remark this answers is not in the document]
Comment (sanderr) [reply src/inmanta/compiler/help/templates/module_v2_in_v1_path.j2:10]: Yeah, I wasn't sure about this. Do you have a suggestion on how to word this?

File: src/inmanta/compiler/help/templates/module_v2_in_v1_path.j2 [hunk 3]
```diff
@@ -0,0 +1,11 @@
...
+- run `inmanta module add {{ name }}` to add the module as a dependency and to install the module if required.
```
[the remark this answers is not in the document]
Comment (sanderr) [reply src/inmanta/compiler/help/templates/module_v2_in_v1_path.j2]: I don't think it is. Even if you're working in editable mode, you'd want to add the dependency to the project, wouldn't you?

[the remark this answers is not in the document]
Comment (sanderr) [reply src/inmanta/compiler/help/templates/module_v2_in_v1_path.j2]: The problem with switching the order is that if the package does not exist yet on an index, the `inmanta module add` would fail. By having this order, you first install everything you want locally, then run the command to add it to the project. Same goes for `inmanta project install`, it would just install any missing dependencies, leaving alone what has already been installed.

[the remark this answers is not in the document]
Comment (arnaudsjs) [reply src/inmanta/compiler/help/templates/module_v2_in_v1_path.j2]: Yes. I agree that the command can stay. I would also make sure that the `inmanta module add` command logs to the console when it overrides an existing installation.

[the remark this answers is not in the document]
Comment (sanderr) [reply src/inmanta/compiler/help/templates/module_v2_in_v1_path.j2]: Good suggestion, I'll add that.

[the remark this answers is not in the document]
Comment (sanderr) [reply src/inmanta/compiler/help/templates/module_v2_in_v1_path.j2]: Though I guess it might not be straightforward, since it is pip that does this, not us.
